/**
* @author        Rey Austral
* @date          10.14.2019
* @description   Class to execute batch job UpdateCRClassificationBatch
* @testClass     UpdateCRClassificationBatchTest
* @revision(s) 
*/
// for deletion
public class UpdateCRClassificationBatchScheduler {} /*implements Schedulable {
	global void execute(SchedulableContext sc) {
		UpdateCRClassificationBatch b = new UpdateCRClassificationBatch();
		database.executebatch(b, 500);
	}
}*/